/// Flutter icons Reportfolio
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Reportfolio
///      fonts:
///       - asset: fonts/Reportfolio.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Reportfolio {
  Reportfolio._();

  static const _kFontFam = 'Reportfolio';
  static const String? _kFontPkg = null;

  static const IconData flutter = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData octicons = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData waving_hand = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codeigniter3 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData figma = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData javascript = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laravel = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData react = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tailwind = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bootstrap_logo = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
