/// Flutter icons Reportfolio
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Reportfolio
///      fonts:
///       - asset: fonts/Reportfolio.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ReportfolioIcons {
  ReportfolioIcons._();

  static const _kFontFam = 'Reportfolio';
  static const String? _kFontPkg = null;

  static const IconData flutter = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData octicons = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wavingHand = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
